function ( install_header_lib )
  set ( OPTIONS )
  set ( VALUES DESTINATION EXPORT COMPONENT )
  set ( MVALUES TARGETS )
  cmake_parse_arguments ( MY "${OPTIONS}" "${VALUES}" "${MVALUES}" ${ARGN} )

  foreach ( TARGET ${MY_TARGETS} )
    get_target_property ( INTERFACE_SOURCES ${TARGET} INTERFACE_SOURCES )
    set ( NEWSOURCES )
    foreach ( S ${INTERFACE_SOURCES} )
      list ( APPEND NEWSOURCES "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/${S}>" "$<INSTALL_INTERFACE:$<INSTALL_PREFIX>${MY_DESTINATION}/${S}>" )
    endforeach ()
    set_target_properties ( ${TARGET} PROPERTIES INTERFACE_SOURCES "${NEWSOURCES}" )
    install ( FILES ${INTERFACE_SOURCES} DESTINATION ${MY_DESTINATION} COMPONENT ${MY_COMPONENT} )
  endforeach ()
  install ( TARGETS ${MY_TARGETS} EXPORT ${MY_EXPORT} )
endfunction ()
